package com.ganhuo.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ganhuo.entity.Ganhuo;

import com.ganhuo.dao.GanhuoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig ganhuoDaoConfig;

    private final GanhuoDao ganhuoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        ganhuoDaoConfig = daoConfigMap.get(GanhuoDao.class).clone();
        ganhuoDaoConfig.initIdentityScope(type);

        ganhuoDao = new GanhuoDao(ganhuoDaoConfig, this);

        registerDao(Ganhuo.class, ganhuoDao);
    }
    
    public void clear() {
        ganhuoDaoConfig.getIdentityScope().clear();
    }

    public GanhuoDao getGanhuoDao() {
        return ganhuoDao;
    }

}
